spring.profiles.active=local
spring.application.name=yoko

# 1. CONEXIÓN A POSTGRESQL (NUBE O LOCAL)
# Sintaxis: ${VARIABLE_DE_RENDER:valor_por_defecto_para_tu_pc}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/yoko_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=org.postgresql.Driver

# Forzamos el dialecto para que Hibernate no se pierda al arrancar
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 2. CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update

# 3. CONFIGURACIÓN DE PGVECTOR (BASE VECTORIAL)
spring.ai.vectorstore.pgvector.initialize-schema=true
# CORREGIDO: multilingual-e5-small usa 384 dimensiones
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# 4. CONFIGURACIÓN DEL LLM (GROQ)
spring.ai.openai.embedding.enabled=false

# === EMBEDDINGS → Transformers local ===
spring.ai.embedding.transformer.onnx.modelUri=https://huggingface.co/intfloat/multilingual-e5-small/resolve/main/onnx/model.onnx
spring.ai.embedding.transformer.tokenizer.uri=https://huggingface.co/intfloat/multilingual-e5-small/resolve/main/tokenizer.json

# Apuntamos a la variable correcta que creamos en Render
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.chat.enabled=true

# Logs detallados para la demo
logging.level.com.yoko=DEBUG
logging.level.org.springframework.ai=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Formato legible en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.output.ansi.enabled=ALWAYS

# ===============================
# CONFIGURACIÓN DE EMAIL (SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Usamos variables de entorno para proteger las credenciales
spring.mail.username=polarisagency.creative@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
