spring.profiles.active=local
spring.application.name=yoko

# 1. CONEXIÓN A POSTGRESQL (DOCKER)
spring.datasource.url=jdbc:postgresql://localhost:5433/yoko_db
spring.datasource.username=admin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CONFIGURACIÓN DE JPA / HIBERNATE
# 'update' crea las tablas automáticamente basándose en tus clases Java (ideal para desarrollo)
spring.jpa.hibernate.ddl-auto=update


# 3. CONFIGURACIÓN DE PGVECTOR (BASE VECTORIAL)

# Spring AI creará la tabla vectorial automáticamente
spring.ai.vectorstore.pgvector.initialize-schema=true
# Las dimensiones dependen del modelo de embeddings que uses (ej. el de HuggingFace o OpenAI suele ser 384, 768 o 1536)
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# 4. CONFIGURACIÓN DEL LLM (GROQ)
spring.ai.openai.embedding.enabled=false

# === EMBEDDINGS → Transformers local ===
spring.ai.embedding.transformer.onnx.modelUri=https://huggingface.co/intfloat/multilingual-e5-small/resolve/main/onnx/model.onnx
spring.ai.embedding.transformer.tokenizer.uri=https://huggingface.co/intfloat/multilingual-e5-small/resolve/main/tokenizer.json

# Configuración para que Groq actúe como OpenAI
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

# MUY IMPORTANTE: Asegúrate de NO haber desactivado el chat por error
spring.ai.openai.chat.enabled=true

# Logs detallados para la demo
logging.level.com.yoko=DEBUG
logging.level.org.springframework.ai=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Formato legible en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Colores en la terminal
spring.output.ansi.enabled=ALWAYS