spring.profiles.active=local
spring.application.name=yoko

# 1. CONEXIÓN A POSTGRESQL (DOCKER)
spring.datasource.url=jdbc:postgresql://localhost:5432/yoko_db
spring.datasource.username=admin
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. CONFIGURACIÓN DE JPA / HIBERNATE
# 'update' crea las tablas automáticamente basándose en tus clases Java (ideal para desarrollo)
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para que veas qué está haciendo por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# 3. CONFIGURACIÓN DE PGVECTOR (BASE VECTORIAL)

# Spring AI creará la tabla vectorial automáticamente
spring.ai.vectorstore.pgvector.initialize-schema=true
# Las dimensiones dependen del modelo de embeddings que uses (ej. el de HuggingFace o OpenAI suele ser 384, 768 o 1536)
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# 4. CONFIGURACIÓN DEL LLM (GROQ)

# Engañamos a Spring AI usando el cliente de OpenAI, pero apuntando a los servidores ultrarrápidos de Groq
spring.ai.openai.base-url=https://api.groq.com/openai/v1
# Usamos una variable de entorno para no subir la llave a GitHub
spring.ai.openai.api-key=${GROQ_API_KEY}
# El modelo que quieras usar en Groq (ej. llama3-8b-8192 o mixtral-8x7b-32768)
spring.ai.openai.chat.options.model=llama3-8b-8192